Yii2/controllers/ClasesController.php
<?php
   
   namespace app\controllers;

use yii\web\Controller;

   class ClasesController extends Controller
   {
       #Layout especial creado en el tutorial 14
       public $layout = 'newlayout';

       public $defaultAction = "index";
    
       public function actions()
       {
           return [
           'test' => 'app\components\TestAction',
        ];
       }
       public function actionIndex()
       {
           return $this->render('../site/index');
       }
       public function actionClass4($message = "Default msg")
       {
           return $this->render("clase4", ['message' => $message]);
       }
       public function actionClass5()
       {
           return $this->render('clase5');
       }
       public function actionClass6()
       {
           return $this->render('clase6');
       }
       public function actionClass8()
       {
           $message = "Default";
           return $this->render("clase8", ['message' => $message ]);
       }
       public function actionClass9()
       {
           return $this->render('clase9');
       }
       public function actionSimple()
       {
           return "<h1>This is a simplistic view</h1>";
       }
       public function actionGoToFb()
       {
           return $this->redirect('http://facebook.com');
       }
       public function actionParameters($fs, $sc)
       {
           return "$fs $sc";
       }
       public function actionClass17()
       {
           return $this->render('clase17');
       }
   }

Yii2/views/clases/clase17.php
<?php
   /* @var $this yii\web\View */
   use kartik\datetime\DateTimePicker;
   use yii\helpers\Html;
   $this->title = 'Clase 17 - Extensiones';
   $this->params['breadcrumbs'][] = $this->title;
   $this->registerMetaTag(['name' => 'keywords', 'content' => 'yii, developing, views,
      meta, tags']);
   $this->registerMetaTag(['name' => 'description',
      'content' => 'This is the description of this page!'], 'description');
?>
<div class="site-about">
   <h1><?= Html::encode($this->title) ?></h1>
   <p>
      This is the About page. You may modify the following file to customize its content:
   </p>
   <?php
      echo DateTimePicker::widget([
         'name' => 'dp_1',
         'type' => DateTimePicker::TYPE_INPUT,
         'value' => '23-Feb-1982 10:10',
         'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'dd-M-yyyy hh:ii'
         ]
      ]);
   ?>
</div>

Yii2/views/clases/clase4.php
<?php 
    
    use yii\helpers\Html; 

    $this->title = 'Class 4 - Create Page';
    echo '<h3> #4: Create Page </h3>'; 
    echo '<b>Your message : </b>'.Html::encode($message);
?> 

<div class="row">
    <h3>Anotaciones de esta clase</h3>
    <p>Para crear una vista en Yii2 se deben manipular las siguientes cosas : </p> 
    <ol>
        <li>
            Se debe crear el archivo de la vista en un fichero PHP, que debera ser guardado en una carpeta
            (al parecer no es mandatario) que coincida con el nombre de su controlador.
            <br> <b>Nota: </b> Controlador se refiere a un objeto que se encuentra en la carpeta 
            {ROOT}/controllers, desde el cual se define el comportamiento de un contexto dentro del framework.
        </li>
        <li>
            Se debe definir una accion en el controlador que tendra la estructura action{Nombre}, (Nombre 
            representa como va a ser el URL de la vista)
            <br> <b>Nota: </b> Accion se refiere a una funcion desde la cual se define no solo el fichero que
            cargara al entrar a la URL que lleve su nombre, sino todos los aspectos adicionales que dicho fichero 
            requiera para su correcto funcionamiento (como variables, y probablemente otros recursos, etc.)
        </li>
        <li>
            Por ultimo, ingresar a la URL {ROOT}/?r={Modulo}/{Controlador}/{Accion}
        </li>
    </ol>
</div>

Yii2/views/clases/clase5.php
<?php 
    
    $this->title = 'Class 5 - Application Structure';
    
?>

<div class="row">
    <h3>Anotaciones de esta clase</h3>
    <p>Yii2 cuenta con un grupo de carpetas que clasifican recursos, las cuales son : </p> 
    <ol>
        <li><b>Assets: </b>Aqui se referencian todos los ficheros .js y .css que la aplicacion utilizara</li>
        <li><b>Commands: </b>Aqui se encuentran todos los controladores que pueden ser usados desde la terminal</li>
        <li><b>Config: </b>Aqui se encuentran los ficheros que contienen la configuracion de la aplicacion</li>
        <li><b>Mail: </b>Aqui se encuentran las plantillas de los correos electronicos</li>
        <li><b>Models: </b>Aqui se incluyen los ficheros de los modelos</li>
        <li><b>Runtime: </b>Aqui se incluye la informacion que se genera en tiempo de ejecucion (e.g. para debugging)</li>
        <li><b>Tests: </b>Aqui se almacenan los ficheros de prueba</li>
        <li><b>Vendor: </b>Aqui estaran todas las carpetas y ficheros que Composer administra</li>
        <li><b>Views: </b>En esta carpeta se posicionan no solo las vistas, sino la plantilla que todas seguiran</li>
        <li><b>Web: </b>Esta es la carpeta publica de la aplicacion, a la cual el usuario tendra acceso</li>
    </ol>
    <p>Ademas, Yii2 utiliza los siguientes objetos : </p> 
    <ol>
        <li><b>Models: </b> Representan la informacion de la capa de persistencia (e.g. PostreSQL)</li>
        <li><b>Views: </b> Muestra dicha informacion al usuario de manera transparente</li>
        <li><b>Controller: </b> Hacen de mediadores entre los dos objetos anteriormente mencionados</li>
        <li><b>Components: </b> Son objetos que contienen logica y pueden ser reutilizados posteriormente.</li>
        <li><b>App. components: </b>Son componentes que solo pueden ser instanciados una vez en toda la aplicacion</li>
        <li><b>Widgets: </b> Son componentes que no solo tienen logica sino que tambien generan una vista</li>
        <li><b>Filters: </b> Son objetos que se ejecutan tanto antes como despues de un controlador</li>
        <li><b>Modules: </b> Son basicamente miniaplicaciones, pues pueden contener todos los objetos anteriores</li>
        <li><b>Extensions: </b> Son los paquetes que pueden ser manejados por Composer</li>
    </ol>
</div>

Yii2/views/clases/clase6.php
<?php 
    
    $this->title = 'Class 6 - Entry Scripts';
    
?>

<div class="row">
    <div class="col-md-6">
        <h3>Anotaciones de esta clase</h3>
        <p>El script de inicio es el eje central de las aplicaciones, ya que en el : </p>
        <ul>
            <li>Se definen las constantes globales</li>
            <li>Se carga el autoloader de Composer</li>
            <li>Se llaman los archivos vitales de Yii2</li>
            <li>Se carga la configuracion de la aplicacion</li>
            <li>Se instancia la aplicacion, y se le aplica la configuracion</li>
            <li>Se procesan las peticiones entrantes</li>
        </ul>
    </div>
    <div class="col-md-6">
        <h3>Como funciona el script de inicio?</h3>
        <p>Este diagrama muestra el comportamiento del script de inicio : </p> 
        <img src="https://www.tutorialspoint.com/yii/images/entry_scripts_structure.jpg">
    </div>
</div>

Yii2/views/clases/clase8.php
<?php 
    
    $this->title = 'Class 8 - Using Controllers';

    echo '<h3> #8: Using Controllers </h3>'; 
    echo '<b>Your message : </b>'.$message;
    
?>

<div class="row">
    <h3>Anotaciones de esta clase</h3>
    <p>Para nombrar un controlador, se deben seguir los siguientes pasos : </p> 
    <ul>
        <li>Volver mayusculas todas las primeras letras de su ID.</li>
        <li>Quitarle todos los guiones que contenga</li>
        <li>Reemplazar los slash por backlashes</li>   
        <li>Añadirle el sufijo "Controller"</li>
        <li>Colocarle el namespace al final del resultado</li>
    </ul>
</div>

Yii2/views/clases/clase9.php
<?php
    use yii\helpers\Url;

$this->title = 'Class 9 - Entry Scripts';
    
?>

<div class="row">
    <div class="col-md-4">
        <h3>Ejemplos de acciones</h3>
        <ul>
            <li><a href="<?= Url::to(['clases/test']) ?>">
                    Acciones independientes (dentro de componentes)</a></li>
            <li><a href="<?= Url::to(['clases/simple']) ?>?r=clases/simple">
                    Acciones con contenido sencillo</a></li>
            <li><a href="<?= Url::to(['clases/go-to-fb']) ?>?r=clases/go-to-fb">
                    Acciones para redireccionar</a></li>
            <li><a href="<?= Url::to(['clases/parameters','fs'=>'Hola','sc'=>'Mundo']) ?>">
                    Acciones con parametros</a></li>
        </ul>
    </div>
    <div class="col-md-8">
        <h3>Anotaciones de esta clase</h3>
        <p>Existen dos tipos de acciones que se pueden crear en Yii2 : acciones independientes o
            acciones de un controlador. Ambas se definen siguiendo los siguientes pasos: </p>
        <ul>
            <li>Volver mayusculas todas las primeras letras de su ID.</li>
            <li>Quitarle todos los guiones que contenga</li>
            <li>Colocarle el sufijo "action" al resultado</li>
        </ul>
        <p>Como se puede apreciar en el menu lateral, las acciones pueden llevar a cabo tareas
            diversas, pero el desarrollador deberia ceñirse a las siguientes recomendaciones: </p>
        <ul>
            <li>Cada accion deberia ser lo mas atomica posible, su escritura no debe ser compleja ni extensa</li>
            <li>Utilizar vistas como respuesta</li>
            <li>No deberia incluir codigo HTML</li>
            <li>Llamar metodos de los modelos</li>
            <li>No procesar informacion. Estos deben ser procesados en los modelos</li>
        </ul>
    </div>
</div>